import Image from 'next/image'
import Head from 'next/head'
import Navbar from '@/components/NavBar/Navbar'
import Main from '@/components/Main/main'
import About from '@/components/About/About'
import Skills from '@/components/Skills/skills'
import Projects from '@/components/Projects/Projects'
import Contact from '@/components/Contact/Contact'
import Blog from './blogs'
export default function Home() {
  return (
    
      <div>
        <Head>
          <title>
            Nayan | Portfolio
          </title>
          <meta name='description' content='Generated by next app' />
          <link rel="icon" href="/favicon.ico"/>
        </Head>
        <div className='px-2'>
        <div><Navbar/></div>
        <div><Main/></div>
        <div><About/></div>
        <div><Skills/></div>
        <div><Projects/></div>
        <div><Blog/></div>
        <div><Contact/></div>
        </div>
        
        

      </div>
      
    
  )
}
